contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #name channel"
    url: https://nfcore.slack.com/channels/name
    about: Discussion about the nf-core/name pipeline
