contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #myworkflow channel"
    url: https://nfcore.slack.com/channels/myworkflow
    about: Discussion about the nf-core/myworkflow pipeline
