contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #workflow_name channel"
    url: https://nfcore.slack.com/channels/workflow_name
    about: Discussion about the nf-core/workflow_name pipeline
