contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #foobar channel"
    url: https://nfcore.slack.com/channels/foobar
    about: Discussion about the nf-core/foobar pipeline
