contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #myworkfow

- [ ]  channel"
    url: https://nfcore.slack.com/channels/myworkfow

- [ ] 
    about: Discussion about the nf-core/myworkfow

- [ ]  pipeline
